Repository owncloud/documentation, pull requests merged in 2018-07, with the labels that each got.

#4235 Firewall logging options
  admin_manual/enterprise/firewall/file_firewall.rst
Labels: Ready for Review

#4248 Document the new legal settings configuration options
  admin_manual/configuration/server/images/owncloud-webui-legal-urls-configuration.png
  admin_manual/configuration/server/index.rst
  admin_manual/configuration/server/legal_settings_configuration.rst
Labels: Enhancement, Ready for Review, p3-medium

#4249 Add user enable-disable to Provisioning API doc
  admin_manual/configuration/user/user_provisioning_api.rst
Labels: WIP

#3799 Remove CleanupChunks background job
  admin_manual/configuration/server/background_jobs_configuration.rst
Labels: Waiting On Review/Feedback

#4259 Update the encryption backup restore encrypted flag documentation
  admin_manual/maintenance/backup.rst
Labels: Ready for Review

#4277 Add Linux log rotation to the logging description
  admin_manual/configuration/server/logging_configuration.rst
Labels: Ready for Review

#4274 Document how to display imprint and privacy policy URLs in a theme
  developer_manual/core/theming.rst
Labels: Ready for Review

#4293 small occ command fixes
  admin_manual/configuration/server/occ_command.rst
Labels: Ready for Review

#4292 new notification template
  admin_manual/configuration/server/email_configuration.rst
Labels: Ready for Review

#4299 Minor changes to the password policy release notes
  admin_manual/release_notes.rst
Labels: Ready for Review

#4300 Improving occ files:scan description for option --path
  admin_manual/configuration/server/occ_command.rst
Labels: Ready for Review

#4289 external storage image
  admin_manual/images/external_storage.png
  admin_manual/images/external_storage_types.png
  admin_manual/images/ftp_storage_support.png
Labels: Ready for Review

#4306 Update the occ maintenance:install example to include the host option
  admin_manual/configuration/server/occ_command.rst
Labels: Enhancement, Incomplete Documentation, Sys Admin, p4-low

#4285 Update password policy documentation
  admin_manual/configuration/server/index.rst
  admin_manual/configuration/server/occ_command.rst
  admin_manual/configuration/server/security/password-policy.rst
  admin_manual/configuration/server/security/password_policy.rst
  admin_manual/images/configuration/server/security/password-policy-app.png
Labels: Ready for Review, p1-urgent

#4314 Script update to example theme download
  developer_manual/scripts/read-config.php
  developer_manual/scripts/theme-bootstrap.sh
Labels: Ready for Review

#4325 Acceptance tests wording when adding context variables
  developer_manual/core/acceptance-tests.rst
Labels: Ready for Review

#4280 Database conversion fix
  admin_manual/configuration/database/db_conversion.rst
Labels: Ready for Review

#4270 addional info added
  admin_manual/appliance/Clamav.rst
Labels: WIP
