Repository owncloud/documentation, pull requests merged in 2018-09, with the labels that each got.

#4389 Update index.rst for occ_apps_command + improve doc headline of config_sample_php_parameters.rst
  admin_manual/configuration/server/config_sample_php_parameters.rst
  admin_manual/configuration/server/index.rst
Labels: occ

#4390 Prepare for config_apps_sample_php_parameters.rst
  admin_manual/configuration/server/config_apps_sample_php_parameters.rst
  admin_manual/configuration/server/index.rst
Labels: Needs More Work

#4414 Update for 10.0.10
  admin_manual/conf.py
  admin_manual/installation/system_requirements.rst
  developer_manual/conf.py
  user_manual/conf.py
Labels: Don't Backport, Enhancement, Waiting On Review/Feedback, p2-high

#4418 Backport update for 10.0.10 release
  admin_manual/conf.py
  admin_manual/installation/system_requirements.rst
  developer_manual/conf.py
  user_manual/conf.py
Labels: On Hold

#4420 Update PHP runtime references for version 7.2
  admin_manual/installation/system_requirements.rst
Labels: Backport to stable10, Enhancement, Ready for Review

#4422 Revise source installation guide for the upgrade to PHP 7.2
  admin_manual/installation/source_installation.rst
Labels: Enhancement, Ready for Review

#4405 Document that occ config:system:set accepts values in JSON format
  admin_manual/configuration/server/occ_command.rst
Labels: Don't Backport, Ready for Review

#4415 Fix navigation for downloading config report
  admin_manual/configuration/server/occ_apps_command.rst
Labels: Admin, Ready to Merge
