Repository owncloud/documentation, pull requests merged in 2018-04, with the labels that each got.

#3864 Augment the dt & dd css style for the ownCloud docs themes
  _shared_assets/themes/owncloud_org/static/styles.css
  _shared_assets/themes/owncloud_release/static/styles.css
Labels: Waiting On Review/Feedback

#3863 Reflow LDAP documentation to follow style guide and fix content mistakes
  admin_manual/configuration/user/user_auth_ldap.rst
Labels: Waiting On Review/Feedback

#3928 Add another conditional log file to log thumbnail access
  admin_manual/installation/nginx_configuration.rst
Labels: Waiting On Review/Feedback

#3594 Change style of active navigation link
  _shared_assets/themes/owncloud_org/static/styles.css
Labels: WIP

#3869 Document that shared hosts are not recommended for deployment
  admin_manual/configuration/server/background_jobs_configuration.rst
  admin_manual/installation/deployment_recommendations.rst
Labels: Waiting On Review/Feedback

#3973 Bump chrome support min to 64
  admin_manual/installation/system_requirements.rst
Labels: Ready for Review

#3911 clarify 'group membership association' vs 'memberof-overlay'
  admin_manual/configuration/user/user_auth_ldap.rst
Labels: WIP

#3972 Add note that internet access is required to activate the appliance
  admin_manual/appliance/installation.rst
Labels: Waiting On Review/Feedback

#3987 Regenerate documentation from config.sample.php
  admin_manual/configuration/server/config_sample_php_parameters.rst
Labels: Ready for Review

#3981 Update php-ldap package in user_auth_ldap
  admin_manual/configuration/user/user_auth_ldap.rst
Labels: Waiting On Review/Feedback

#3970 Correct the Redis code block example
  admin_manual/configuration/server/caching_configuration.rst
Labels: Waiting On Review/Feedback

#3971 Link the enterprise server branding to the theming documentation
  admin_manual/enterprise/server_branding/enterprise_server_branding.rst
Labels: Waiting On Review/Feedback

#3983 images folder "setup"
  admin_manual/images/appliance/setup/readme.md
Labels: Waiting On Review/Feedback

#3984 Update how to install the appliance
  admin_manual/appliance/installation.rst
Labels: Waiting On Review/Feedback

#4010 Correct references to the Versions app use of a user's quota
  admin_manual/configuration/files/file_versioning.rst
  user_manual/files/deleted_file_management.rst
Labels: Waiting On Review/Feedback

#4011 Update references to the external apps directory
  admin_manual/installation/apps_management_installation.rst
  admin_manual/installation/examples/custom-app-directory-configuration.php
  admin_manual/installation/examples/post-installation-steps.sh
  admin_manual/installation/installation_wizard.rst
  developer_manual/core/configfile.rst
Labels: Ready to Merge

#4019 Set version to 10.0.8
  user_manual/conf.py
Labels: Ready for Review

#3982 brought password options
  admin_manual/enterprise/external_storage/windows-network-drive_configuration.rst
Labels: WIP, Waiting On Review/Feedback

#4016 added a note about rpcbind in the appliance
  admin_manual/appliance/installation.rst
Labels: WIP

#4039 Document how to disable code coverage
  developer_manual/core/unit-testing.rst
Labels: Ready for Review

#4070 Document the occ notifications command
  admin_manual/configuration/server/occ_command.rst
Labels: Ready to Merge

#4083 Document the files:checksums:verify command
  admin_manual/configuration/server/occ_command.rst
Labels: Waiting On Review/Feedback

#4084 added conf dir
  admin_manual/appliance/login_information.rst
Labels: WIP

#4076 10.0.8 Release Notes
  admin_manual/release_notes.rst
Labels: WIP

#4095 webUI tests must always be run by suite
  developer_manual/core/ui-testing.rst
Labels: Dev
