Repository owncloud/documentation, pull requests merged in 2018-06, with the labels that each got.

#4175 Add semicolons to the end of mysql commands
  developer_manual/core/unit-testing.rst
Labels: Ready to Merge

#4167 add shared_with_me request attribute
  developer_manual/core/ocs-share-api.rst
Labels: Ready to Merge

#4177 Backport: add shared_with_me request attribute
  developer_manual/core/ocs-share-api.rst
Labels: Backport to stable10

#3464 Draft OAuth2 Documenation
  admin_manual/configuration/server/security/oauth2.rst
  admin_manual/installation/source_installation.rst
Labels: WIP, Waiting On Review/Feedback

#4173 Update occ user:sync command
  admin_manual/configuration/server/occ_command.rst
Labels: WIP

#4165 Added LDAP memberof-filter
  admin_manual/configuration/user/user_auth_ldap.rst
Labels: WIP

#4174 appliance-firewall
  admin_manual/appliance/firewall.rst
  admin_manual/appliance/index.rst
Labels: WIP

#4170 enterprise-trial
  admin_manual/appliance/enterprise-trial.rst
Labels: WIP

#4169 Create encryption_configuration_quick_guide.rst
  admin_manual/configuration/files/encryption_configuration_quick_guide.rst
Labels: WIP

#4187 Correct indent of capabilities example
  developer_manual/core/ocs-capabilities.rst
Labels: Ready for Review

#4186 Included multiple servers - config.php
  admin_manual/installation/deployment_considerations.rst
Labels: Ready to Merge

#4160 Instructions for running local UI acceptance tests with docker
  developer_manual/core/ui-testing.rst
Labels: Ready for Review

#4164 Document split public password enforced capabilities
  developer_manual/core/ocs-capabilities.rst
Labels: Ready to Merge

#4196 Update the minimum PHP version requirements
  admin_manual/installation/source_installation.rst
  admin_manual/installation/system_requirements.rst
Labels: Ready for Review

#4200 System requirements for 10.0.9
  admin_manual/installation/system_requirements.rst
Labels: Ready for Review

#4209 Use public URL for submodule
  .gitmodules
Labels: Ready for Review

#4210 [stable10] Use public URL for submodule
  .gitmodules
Labels: Ready for Review

#4216 Document files:scan --groups
  admin_manual/configuration/server/occ_command.rst
Labels: Ready for Review

#4227 Set versions to 10.0.9
  admin_manual/conf.py
  developer_manual/conf.py
  user_manual/conf.py
Labels: Ready for Review

#3187 Document SAML 2.0 based SSO with ADFS and mod_shib
  admin_manual/enterprise/user_management/saml_2.0_sso.rst
Labels: WIP, Waiting On Review/Feedback, p4-low

#2938 Update how to enable the recovery key password for version 10.0.
  admin_manual/configuration/files/encryption_configuration.rst
  admin_manual/configuration/files/images/encryption7.png
Labels: Encryption, Ready for Review, Waiting On Review/Feedback, p4-low
