Repository owncloud/documentation, pull requests merged in 2018-02, with the labels that each got.

#3779 Conditional Logging description improvements
  admin_manual/configuration/server/config_sample_php_parameters.rst
  admin_manual/configuration/server/logging_configuration.rst
Labels: Ready to Merge

#3786 Document that the installation wizard should not be left unprotected
  admin_manual/installation/installation_wizard.rst
Labels: Ready for Review

#3764 New and more flexible setting ownership and permissions script
  admin_manual/installation/installation_wizard.rst
Labels: Ready for Review

#3718 Update the linux package manager installation instructions
  admin_manual/installation/index.rst
  admin_manual/installation/linux_installation.rst
Labels: Waiting On Review/Feedback

#3818 Document when stable packages are updated
  admin_manual/installation/source_installation.rst
Labels: Waiting On Review/Feedback

#3838 Update 10.0.7 release notes with known issue about app password
  admin_manual/conf.py
  admin_manual/release_notes.rst
  developer_manual/conf.py
  user_manual/conf.py
Labels: Waiting On Review/Feedback

#3842 Bump firefox min version to 57
  admin_manual/installation/system_requirements.rst
Labels: Ready for Review

#3832 Update of the installation-wizard page
  admin_manual/installation/examples/post-installation-steps.sh
  admin_manual/installation/installation_wizard.rst
Labels: Waiting On Review/Feedback

#3826 Remove dead link from Shibboleth documentation
  admin_manual/enterprise/user_management/user_auth_shibboleth.rst
Labels: Waiting On Review/Feedback

#3821 Update system_requirements.rst
  admin_manual/installation/system_requirements.rst
Labels: Waiting On Review/Feedback

#3808 Added some command examples
  admin_manual/enterprise/external_storage/windows-network-drive_configuration.rst
Labels: Waiting On Review/Feedback

#3850 Adding a note in files:scan about the --path option and mounts recieved
  admin_manual/configuration/server/occ_command.rst
Labels: Waiting On Review/Feedback
