Repository owncloud/documentation, pull requests merged in 2018-05, with the labels that each got.

#4120 Document putting a user in groups when they are being created
  admin_manual/configuration/user/user_provisioning_api.rst
Labels: Ready for Review

#4122 Set the end copyright year automagically
  admin_manual/conf.py
  developer_manual/conf.py
  user_manual/conf.py
Labels: Waiting On Review/Feedback

#4130 Document that some apps cannot be disabled
  admin_manual/configuration/server/occ_command.rst
Labels: Waiting On Review/Feedback

#4106 Link to new location of the example theme
  developer_manual/core/theming.rst
Labels: Ready to Merge

#4146 Document newer layout of acceptance test folders
  developer_manual/core/acceptance-tests.rst
Labels: Ready for Review

#4144 Document opcache.revalidate_freq=0 for acceptance tests
  developer_manual/core/acceptance-tests.rst
Labels: Ready for Review

#4171 Add note about templateeditor unbundling
  admin_manual/release_notes.rst
Labels: Ready to Merge
