Repository owncloud/documentation, pull requests merged in 2018-03, with the labels that each got.

#3865 Revise the guest application documentation
  user_manual/files/webgui/sharing.rst
  user_manual/images/guest-users/content-shared-with-guest-user.png
  user_manual/images/guest-users/share-with-guest-users.png
Labels: Waiting On Review/Feedback

#3880 Encourage users to store themes in a custom app directory
  developer_manual/core/theming.rst
Labels: Waiting On Review/Feedback

#3765 fix ownCloud in a subdir of NGINX configuration
  admin_manual/installation/nginx_configuration.rst
Labels: Waiting On Review/Feedback

#3892 Move of UI acceptance tests into acceptance folder
  developer_manual/core/ui-testing.rst
Labels: Ready for Review

#3871 Document the need to review the mandatory requirements before upgrading
  admin_manual/maintenance/manual_upgrade.rst
Labels: Waiting On Review/Feedback

#3894 Tidy up the NGINX documentation
  admin_manual/installation/examples/nginx/default-configuration.conf
  admin_manual/installation/examples/nginx/subdirectory-configuration.conf
  admin_manual/installation/nginx_configuration.rst
  admin_manual/issues/general_troubleshooting.rst
Labels: WIP

#3929 Updated the php-smbclient to the codeblock
  admin_manual/enterprise/external_storage/windows-network-drive_configuration.rst
Labels: WIP

#3917 only match login at the beginning of the url
  admin_manual/enterprise/user_management/user_auth_shibboleth.rst
Labels: Waiting On Review/Feedback

#3939 Appliance login information
  admin_manual/appliance/login_information.rst
Labels: Waiting On Review/Feedback

#3946 Fix & reorganise developer doc help links
  developer_manual/commun/help_and_communication.rst
Labels: Ready for Review

#3942 Update the Clamav appliance doc
  admin_manual/appliance/Clamav.rst
  admin_manual/images/appliance/ucs/clamav/confirm-clamav-installation.png
  admin_manual/images/appliance/ucs/clamav/install-clamav.png
Labels: Ready for Review

#3913 Configuring Letsencrypt with Apache/NGINX for ownCloud
  admin_manual/installation/examples/lets_encrypt/cli.ini
  admin_manual/installation/examples/lets_encrypt/delete.sh
  admin_manual/installation/examples/lets_encrypt/list.sh
  admin_manual/installation/examples/lets_encrypt/renew-cron.sh
  admin_manual/installation/examples/lets_encrypt/renew.sh
  admin_manual/installation/examples/lets_encrypt/your-domain-name.sh
  admin_manual/installation/images/ssllabs.png
  admin_manual/installation/index.rst
  admin_manual/installation/letsencrypt/apache.rst
  admin_manual/installation/letsencrypt/index.rst
  admin_manual/installation/letsencrypt/nginx.rst
Labels: WIP
