Repository owncloud/documentation, pull requests merged in 2018-08, with the labels that each got.

#4320 Document the ability to blacklist groups from receiving shares
  admin_manual/configuration/files/file_sharing_configuration.rst
  admin_manual/configuration/files/images/sharing/blacklisting-groups.png
Labels: Waiting On Review/Feedback

#3949 Backport: voroyam upgrade owncloud
  admin_manual/maintenance/manual_upgrade.rst
  admin_manual/maintenance/upgrade.rst
Labels: Waiting On Review/Feedback

#4338 Document sharing notification language configuration
  admin_manual/configuration/files/file_sharing_configuration.rst
Labels: Ready for Review

#4347 Acceptance tests minor doc bugs
  developer_manual/core/acceptance-tests.rst
  developer_manual/core/ui-testing.rst
Labels: Ready for Review

#4312 Mimetypes Management addition to theming
  developer_manual/core/theming.rst
Labels: WIP

#4269 added new features in custom groups
  user_manual/files/webgui/custom_groups.rst
Labels: Waiting On Review/Feedback

#4290 Update external_storage_configuration_gui.rst
  admin_manual/configuration/files/external_storage/ftp.rst
  admin_manual/configuration/files/external_storage_configuration_gui.rst
Labels: WIP

#4361 update occ comand list for files external
  admin_manual/configuration/server/occ_command.rst
Labels: WIP

#4317 appliance-82-migration
  admin_manual/appliance/howto-update-owncloud.rst
Labels: WIP

#4318 Note about an error in collabora
  admin_manual/appliance/Office.rst
Labels: WIP

#4339 Update documentation for files_primary_s3
  admin_manual/enterprise/external_storage/s3_swift_as_primary_object_store_configuration.rst
Labels: Ready for Review, p2-high

#4378 Improvements of occ files_external commands documentation
  admin_manual/configuration/server/occ_command.rst
Labels: Ready for Review, occ

#4381 Splitting occ_command.rst into two files for core and apps
  admin_manual/configuration/server/occ_apps_command.rst
  admin_manual/configuration/server/occ_command.rst
Labels: Enhancement, occ

#4395 _old_shared_assets typos
  _old_shared_assets/themes/owncloud_com/layout.html
  _old_shared_assets/themes/owncloud_com/static/css/bootstrap.css
  _old_shared_assets/themes/owncloud_com/static/less/forms.less
  _old_shared_assets/themes/owncloud_com/static/less/labels-badges.less
  _old_shared_assets/themes/owncloud_com/static/less/navbar.less
  _old_shared_assets/themes/owncloud_com/static/less/navs.less
  _old_shared_assets/themes/owncloud_com/static/less/reset.less
  _old_shared_assets/themes/owncloud_com/static/less/responsive-767px-max.less
  _old_shared_assets/themes/owncloud_com/static/less/thumbnails.less
  _old_shared_assets/themes/owncloud_org/static/bootstrap-sphinx.css_t
  _old_shared_assets/themes/owncloud_release/static/bootstrap-sphinx.css_t
Labels: Ready for Review

#4394 Typos noticed in various places
  admin_manual/configuration/database/linux_database_configuration.rst
  admin_manual/configuration/files/big_file_upload_configuration.rst
  admin_manual/configuration/ldap/ldap_proxy_cache_server_setup.rst
  admin_manual/configuration/server/logging_configuration.rst
  admin_manual/configuration/server/security_setup_warnings.rst
  admin_manual/enterprise/external_storage/windows-network-drive_configuration.rst
  admin_manual/enterprise/user_management/user_auth_shibboleth.rst
  admin_manual/installation/apps_supported.rst
  admin_manual/installation/nginx_configuration.rst
  admin_manual/installation/system_requirements.rst
  admin_manual/maintenance/update.rst
  bin/unix/install-dependencies/archlinux.sh
  bin/unix/install-dependencies/debian-ubuntu.sh
  bin/unix/install-dependencies/opensuse.sh
  developer_manual/app/fundamentals/container.rst
  developer_manual/app/tutorial/testing.rst
  developer_manual/core/configfile.rst
  developer_manual/core/theming.rst
  developer_manual/core/unit-testing.rst
  developer_manual/examples/php/vendor/guzzlehttp/guzzle/UPGRADING.md
  developer_manual/examples/php/vendor/guzzlehttp/promises/src/functions.php
  developer_manual/examples/php/vendor/guzzlehttp/promises/tests/FulfilledPromiseTest.php
  developer_manual/examples/php/vendor/guzzlehttp/promises/tests/RejectedPromiseTest.php
  developer_manual/examples/php/vendor/guzzlehttp/psr7/tests/UriTest.php
  developer_manual/mobile_development/ios_library/examples.rst
  developer_manual/scripts/theme-bootstrap.sh
Labels: Ready for Review

#4391 config_sample_php_parameters typos
  admin_manual/configuration/server/config_sample_php_parameters.rst
Labels: Ready for Review

#4401 [stable10] Typos noticed in various places
  admin_manual/configuration/database/linux_database_configuration.rst
  admin_manual/configuration/files/big_file_upload_configuration.rst
  admin_manual/configuration/ldap/ldap_proxy_cache_server_setup.rst
  admin_manual/configuration/server/security_setup_warnings.rst
  admin_manual/enterprise/external_storage/windows-network-drive_configuration.rst
  admin_manual/enterprise/user_management/user_auth_shibboleth.rst
  admin_manual/installation/apps_supported.rst
  admin_manual/installation/nginx_configuration.rst
  admin_manual/installation/system_requirements.rst
  admin_manual/maintenance/update.rst
  bin/unix/install-dependencies/archlinux.sh
  bin/unix/install-dependencies/debian-ubuntu.sh
  bin/unix/install-dependencies/opensuse.sh
  developer_manual/app/fundamentals/container.rst
  developer_manual/app/tutorial/testing.rst
  developer_manual/core/configfile.rst
  developer_manual/core/theming.rst
  developer_manual/core/unit-testing.rst
  developer_manual/examples/php/vendor/guzzlehttp/guzzle/UPGRADING.md
  developer_manual/examples/php/vendor/guzzlehttp/promises/src/functions.php
  developer_manual/examples/php/vendor/guzzlehttp/promises/tests/FulfilledPromiseTest.php
  developer_manual/examples/php/vendor/guzzlehttp/promises/tests/RejectedPromiseTest.php
  developer_manual/examples/php/vendor/guzzlehttp/psr7/tests/UriTest.php
  developer_manual/mobile_development/ios_library/examples.rst
Labels: Ready for Review
