Repository owncloud/documentation, pull requests merged in 2018-11, with the labels that each got.

#4462 Backport Updates to Classification and Policy Enforcement
  admin_manual/enterprise/classification_and_policy_enforcement.rst
Labels: Backport to stable10

#4473 [stable10] Remove sudo www-data from acceptance test instructions
  developer_manual/core/acceptance-tests.rst
  developer_manual/core/ui-testing.rst
Labels: Ready for Review

#4472 Remove sudo www-data from acceptance test instructions
  developer_manual/core/acceptance-tests.rst
  developer_manual/core/ui-testing.rst
Labels: Backport to stable10, Ready for Review
